# Generated by Django 4.2.1 on 2023-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_remove_question_correct_option_option_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
