# Generated by Django 4.2.1 on 2023-05-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_remove_question_answer_option_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
