# Generated by Django 4.2.1 on 2023-05-31 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0009_remove_option_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
